### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/openexr-feedstock#1]
Raising as it would be great to have a Windows build. Are there specific issues that need to be addressed to achieve this?

**Comment by SylvainCorlay** [comment]
Yes and no. I will detail in the PR, which I am opening after the rebuild PR is in!

**Comment by jakirkham** [comment]
Thanks @SylvainCorlay 😄

**Comment by jakirkham** [comment]
Ah, now I see [this comment]( https://github.com/conda-forge/staged-recipes/pull/7088#issuecomment-441396287 ). So it will require some patching of the build system to get it to detect `ilmbase` on Windows.

I wonder if that is the easiest path or if we should turn this into a split package, which builds everything.

**Comment by SylvainCorlay** [comment]
Their cmake is very complicated (and very complicated) for a project that small.

**Comment by npavlovikj** [comment]
Yeah, considering the many cmake issues, I agree with @jakirkham that maybe having a separate Windows package that builds everything is easier option.

**Comment by SylvainCorlay** [comment]
Will open the PR as soon as the rebuild PR is in.

Also, I will give another shot at getting the right incantations for this to build properly on windows.
