### ISSUE TITLE
OpenEXR 3.3.1 is shipping libdeflate and clobbering things

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/openexr-feedstock#49]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Fopenexr-3.3.1-h6ed009d_0.conda
see logs from
https://github.com/conda-forge/opencv-feedstock/pull/436

### Installed packages

conda-forge/linux-64::openexr-3.3.1-h6ed009d_0.conda

### Environment info

conda-forge/linux-64::openexr-3.3.1-h6ed009d_0.conda

**Comment by hmaarrfk** [comment]
this change to finding the package was introduced in 3.3.0 
https://github.com/AcademySoftwareFoundation/openexr/commit/cb94fe1dfc29e189363c59b597723e5066e7b3ac

The previous version we built was 3.2.X

**Comment by minrk** [comment]
I would think you should start getting the fixed builds once it makes its way through the CDN (this has been my experience in other conda-forge builds so far today), but yes: https://github.com/conda-forge/admin-requests/pull/1105
